@startuml

title __PRESENTATION's Class Diagram__\n

  namespace presentation {
    class presentation.ExitConsole {
        + execute()
    }
  }
  

  namespace presentation {
    class presentation.InputReader {
        + reader : BufferedReader
        ~ commandList : String
        + InputReader()
        + getNextCommand()
    }
  }
  

  namespace presentation {
    class presentation.MakeComplexExperiment {
        ~ experimentID : String
        ~ quantity : String
        ~ supplyItem : String
        ~ target : String
        ~ whatToDo : String
        + execute()
        + getType()
    }
  }
  

  namespace presentation {
    class presentation.MakeReagentExperiment {
        ~ experimentID : String
        ~ measurementsToTake : String
        ~ reagent : String
        ~ reagentQuantity : String
        ~ sampleToApplyTo : String
        + execute()
        + getType()
    }
  }
  

  namespace presentation {
    class presentation.MakeSampleExperiment {
        ~ experimentID : String
        ~ howMuchToSample : String
        ~ whatToSample : String
        ~ whereToSample : String
        + execute()
        + getType()
    }
  }
  

  namespace presentation {
    class presentation.ProcessReagentExperiment {
        ~ sampleID : String
        + execute()
        - printValidReagentExperiments()
    }
  }
  

  namespace presentation {
    class presentation.ProcessSampleExperiment {
        + execute()
        + getType()
        - printValidSampleExperiments()
    }
  }
  

  namespace presentation {
    interface presentation.UIProcess {
        {abstract} + execute()
    }
  }
  

  presentation.ExitConsole .up.|> presentation.UIProcess
  presentation.MakeComplexExperiment .up.|> presentation.UIProcess
  presentation.MakeReagentExperiment .up.|> presentation.UIProcess
  presentation.MakeSampleExperiment .up.|> presentation.UIProcess
  presentation.ProcessReagentExperiment .up.|> presentation.UIProcess
  presentation.ProcessSampleExperiment .up.|> presentation.UIProcess


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
